TraceRoute: main.cpp
	c++ main.cpp -o TraceRoute
clean: *.o
	echo "Clean called"
	rm *.o
fclean: TraceRoute
	echo "FClean called"
	rm TraceRoute
re: fclean
	echo "Re called"
	c++ main.cpp -o TraceRoute